# Dockerfile for image: pyleman2000-matlab-runtime:custom
# 
# Sample docker build command:
# docker build -f "Dockerfile.runtime" -t pyleman2000-matlab-runtime:custom "."

FROM containers.mathworks.com/matlab-runtime-utils/matlab-runtime-installer:r2026a-update-4 AS installer
LABEL "mathworks.matlab.runtime.cleanup"="true"

ENV EXTRACTEDDIR="/opt/matlabruntime/unzippedinstaller"

WORKDIR $EXTRACTEDDIR

# Write the installer file
RUN touch ./installInputs.txt
RUN printf "destinationFolder=/tmp/matlabruntime/runtime\nagreeToLicense=yes\n" > ./installInputs.txt
RUN printf "product.MATLAB Extended Runtime Addon\n" >> ./installInputs.txt
RUN printf "product.MATLAB Graphics Runtime Addon\n" >> ./installInputs.txt
RUN printf "product.MATLAB Standard Runtime Addon\n" >> ./installInputs.txt
RUN printf "product.MATLAB Base Runtime\n" >> ./installInputs.txt
RUN printf "product.Signal Processing Toolbox Runtime Addon\n" >> ./installInputs.txt
RUN printf "product.DSP System Toolbox Runtime Addon\n" >> ./installInputs.txt

# Run the installer
RUN ./install -bat true -inputFile ./installInputs.txt

FROM matlabruntimebase/r2026a/release/update4
LABEL "mathworks.matlab.runtime.cleanup"="false"

RUN apt-get update && apt-get upgrade -y

ENV TZ="Etc/UTC"

COPY --from=installer /tmp/matlabruntime/runtime /opt/matlabruntime

RUN unlink /opt/matlabruntime/R2026a/sys/os/glnxa64/libstdc++.so.6
RUN ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /opt/matlabruntime/R2026a/sys/os/glnxa64/libstdc++.so.6

ENV LD_LIBRARY_PATH="/opt/matlabruntime/R2026a/runtime/glnxa64:/opt/matlabruntime/R2026a/bin/glnxa64:/opt/matlabruntime/R2026a/sys/os/glnxa64:/opt/matlabruntime/R2026a/sys/opengl/lib/glnxa64:/opt/matlabruntime/R2026a/extern/bin/glnxa64"

